export const CREATE_PROJECT_START_LOADING = 'CREATE_PROJECT_START_LOADING'
export const CREATE_PROJECT_END_LOADING = 'CREATE_PROJECT_END_LOADING'
export const PROJECT_CHANGE_DATELINES = 'PROJECT_CHANGE_DATELINES'