export const PROJECTS_GET = 'PROJECTS_GET'
export const PROJECTS_LOADING_START = 'PROJECTS_LOADING_START'
export const PROJECTS_LOADING_END = 'PROJECTS_LOADING_END'
export const PROJECTS_LOADED = 'PROJECTS_LOADED'
export const PROJECTS_UNLOADED = 'PROJECTS_UNLOADED'

export const PROJECTS_ADD = 'PROJECTS_ADD'
